### ISSUE TITLE
The query result could not be shown in result zone due to Chrome Content Security Policy.

### ISSUE THREAD

**Issue by swisszhang** [TravisTX/elasticsearch-head-chrome#1]
In query tab, any ES query failed to perform. The error is "Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'sha256-Rpn+rjJuXCjZBPOPhhVloRXuzAUBRnAas+6gKVDohs0='"."

In browser debug mode, the query request and response actually returned. But the query result could not be shown in result zone due to Chrome CSP.

![image](https://user-images.githubusercontent.com/10009531/28856842-dd28b3b4-7777-11e7-923d-e84ff994ee9d.png)

**Comment by j0hnsmith** [comment]
@swisszhang I think you can get around it by

```
socat TCP-LISTEN:9200,fork,reuseaddr TCP:10.110.4.172:9200
```

then use `http://localhost:9200` in the connect box.

**Comment by j0hnsmith** [comment]
@TravisTX Note that I couldn't get this solution to work when elasticsearch was on a https url.

**Comment by swisszhang** [comment]
@TravisTX I think the answer above is just a workaround, not a fix. Currently I have lots of ES, and 'socat' on every instance seems not practical. Is there any way to fix the security issue?

**Comment by swisszhang** [comment]
@j0hnsmith My issue is fixed in ccc0002, thanks for the workaround provided anyway.
