### ISSUE TITLE
Please fix the failure of sorting nodes by address

### ISSUE THREAD

**Issue by Starwalker2000** [TravisTX/elasticsearch-head-chrome#17]
Can you please merge this commit: [02ebf12](https://github.com/mobz/elasticsearch-head/commit/02ebf121e758167d91cec6ea04f3d957b00b57ff)
Because of this issue: [Fail to sort nodes by address when there are unassigned shards](https://github.com/mobz/elasticsearch-head/commit/02ebf121e758167d91cec6ea04f3d957b00b57ff)

**Comment by TravisTX** [comment]
I merged this and updated the extension on the chrome store.  It might take up to 60 minutes to begin showing.
