### ISSUE TITLE
Never shows results of search

### ISSUE THREAD

**Issue by rodrigopaulino** [TravisTX/elasticsearch-head-chrome#2]
I'm trying to perform a simple search on my index, but the result is never shown and the "Requesting..." message never leaves. This was my first attempt to run the plugin and all my indices are listed with the correct amount of documents indexed.
I'm using: 
Chrome Version 59.0.3071.115
Elasticsearch 2.4.0

<img width="565" alt="screen shot 2017-08-10 at 13 05 59" src="https://user-images.githubusercontent.com/11450348/29180078-fb7d4f4a-7dcc-11e7-9af0-81bc0fffdec4.png">

**Comment by TravisTX** [comment]
If you hit F12 to open the Chrome debug tools, do you see anything in the console or network tab that could hint at what the issue could be?

**Comment by rodrigopaulino** [comment]
I'm getting 403 (forbidden) response from the search request.

**Comment by TravisTX** [comment]
I'm not able to reproduce this, but I'm on elastic 5x.  A lot has changed in elastic since 2.4.  With 2.4, I'd recommend installing elasticsearch-head as an elastic extension.  Or upgrade to 5x (easier said than done, I know).  Sorry I can't be of more help.
