### ISSUE TITLE
ES 7

### ISSUE THREAD

**Issue by AzVedi** [TravisTX/elasticsearch-head-chrome#24]
Look like head not work with ES 7.*

![head-es7](https://user-images.githubusercontent.com/13836023/62543514-b2f3ae00-b866-11e9-8f51-3e7abcc654c3.png)

**Comment by philipskokoh** [comment]
This issue has been resolved in the latest [elasticsearch-head](https://github.com/mobz/elasticsearch-head) code (see commit https://github.com/mobz/elasticsearch-head/commit/ff13f89693521ec7d0c1880fe098464b635650e2 for more details).

@TravisTX, could you help to update the chrome extension with the latest code from elasticsearch-head repo?  I think many people start to use the new Elasticsearch 7.x.
