### ISSUE TITLE
Chrome Extension shows 2nd Master as a Worker

### ISSUE THREAD

**Issue by bcharboneauiherb** [TravisTX/elasticsearch-head-chrome#4]
I am using an AWS Elastic Search Service, which i have 2 masters and 6 data nodes. In the Extension 1 of my Masters shows as a Data Node with the Circle icon instead of a star icon. 

i have confirmed by viewing node stats that it has the role of "master" and not "data". See attached screenshots

![image](https://user-images.githubusercontent.com/25490249/32030107-a82418f2-b9ad-11e7-8105-70ae06e8d018.png)

![image](https://user-images.githubusercontent.com/25490249/32030168-12c5ef6e-b9ae-11e7-989b-bfd9b288b6fa.png)

**Comment by TravisTX** [comment]
Sorry this extension is just a very thin wrapper around elasticsearch-head.  Any issues with es-head, should probably go to that repo.
