### ISSUE TITLE
Content-Type 'application/x-www-form-urlencoded' not supported on elastic 6.0.0

### ISSUE THREAD

**Issue by pokerjocke70** [TravisTX/elasticsearch-head-chrome#5]
When using the chrome extension on an elastic 6.0.0 cluster every search fails with a:

{
"error": "Content-Type header [application/x-www-form-urlencoded] is not supported",
"status": 406
}

Works on old elastic versions.

**Comment by nczz** [comment]
Hi @TravisTX ,

Same issue.

**Comment by priteshkp** [comment]
Probably due to:
https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests

**Comment by priteshkp** [comment]
Created this fix (tested locally by modifying the file): https://github.com/TravisTX/elasticsearch-head-chrome/pull/6

**Comment by TravisTX** [comment]
Merged. Thanks @priteshkp
